### ISSUE TITLE
YC container registry

### ISSUE THREAD

**Issue by egchernousov** [pyropy/yandex-cloud-image-registry#109]
Can you help me to use your action to build and push docker container to YC registry? It would be nice if you gave an example .yml file with your action.

**Comment by pyropy** [comment]
Hi,

Here's an example of the github actions file:

```yml

name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Upload Image to Yandex Image Registry Action
        uses: pyropy/yandex-cloud-image-registry@v0.8-alpha
        with:
          YC_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.YC_SERVICE_ACCOUNT_KEY_FILE }}
          YC_IMG_REGISTRY_ID: ${{ secrets.YC_IMG_REGISTRY_ID }}
          DOCKER_CONTEXT: "./"
          DOCKER_IMG_NAME: "backend"
```
